name: Publish docs via GitHub Pages

on: [push]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/stacchip
    permissions:
      id-token: write
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine build hatch
      - name: Build distribution
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/